name: Test
on:
  push:
    branches:
      - main
    paths:
      - _contents/**
      - blog-app/data/**
      - blog-app/components/**
      - blog-app/pages/**
      - blog-app/libs/**
      - blog-app/public/**
      - blog-app/tests/**
      - blog-app/styles/**

  pull_request:

env:
  working-directory: ./blog-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      - name: Test
        run: pnpm test:ci
        working-directory: ${{ env.working-directory }}

      - name: Export Next.js 
        run: pnpm export
        working-directory: ${{ env.working-directory }}

      - name: Test Coverage
        run: pnpm run test:coverage
        working-directory: ${{ env.working-directory }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ env.working-directory }}/coverage/lcov.info
          